FORMAT: 1A
HOST: https://api.sac.digital

# Listar Contactos


## Questions Collection [/v2/client/contact/all]


### Listar Contatos [GET]
Metodo para Listar Contatos

+ Request (application/json)


    

+ Response 200 (application/json)